"""
Django settings for Disaster project (Render-ready).

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# -----------------------
# Load environment variables
# -----------------------
load_dotenv()  # Must be at the very top

# -----------------------
# Base directory
# -----------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------
# Environment variables
# -----------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "fallback-secret-key")
DEBUG = os.environ.get("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Add Render domains if in production
if not DEBUG:
    ALLOWED_HOSTS.extend([
        ".onrender.com",
        ".render.com"
    ])

# -----------------------
# Installed apps
# -----------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'frontend',
    'backend',
    'mlmodel',
    "corsheaders",
]

# -----------------------
# Middleware
# -----------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------
# URLs & Templates
# -----------------------
ROOT_URLCONF = 'Disaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Disaster.wsgi.application'

# -----------------------
# Database (PostgreSQL)
# -----------------------
DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get(
            "DATABASE_URL",
            # Fallback to local PostgreSQL credentials (URL-encoded @)
            "postgres://postgres:supash%4016@localhost:5432/disaster_db"
        ),
        conn_max_age=600
    )
}

# -----------------------
# Password validation
# -----------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------
# Internationalization
# -----------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------
# Static & media files
# -----------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------
# Authentication
# -----------------------
AUTH_USER_MODEL = "backend.CustomUser"
LOGIN_REDIRECT_URL = '/view_report/'
LOGOUT_REDIRECT_URL = 'home'

# -----------------------
# CORS
# -----------------------
CORS_ALLOW_ALL_ORIGINS = DEBUG  # allow all origins in development
if not DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "https://disaster-management.onrender.com",
        "https://*.onrender.com",
    ]

# -----------------------
# App constants
# -----------------------
INDIA_BOUNDS = {
    "MIN_LAT": 6.0, "MAX_LAT": 37.5,
    "MIN_LNG": 68.0, "MAX_LNG": 97.5,
}
