services:
  - type: web
    name: disaster-management
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "disaster-management.onrender.com"
    healthCheckPath: /
