# Generated by Django 5.2.5 on 2025-09-03 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flood', 'flood'), ('landslide', 'landslide'), ('roadblock', 'roadblock'), ('medical', 'medical'), ('other', 'other'), ('earthquake', 'earthquake'), ('cyclone', 'cyclone'), ('tsunami', 'tsunami'), ('drought', 'drought'), ('wildfires', 'wildfires')], default='other', max_length=32)),
                ('severity', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('note', models.CharField(blank=True, max_length=240)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('device_fingerprint', models.CharField(blank=True, max_length=128)),
                ('eq_magnitude', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cyclone_wind_kmh', models.IntegerField(blank=True, null=True)),
                ('tsunami_wave_m', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('drought_days', models.IntegerField(blank=True, null=True)),
                ('wildfire_ha', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CrowdReport',
        ),
        migrations.DeleteModel(
            name='Disaster',
        ),
    ]
