# Generated by Django 5.2.5 on 2025-09-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_report_delete_crowdreport_delete_disaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('roadblock', 'Roadblock'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
