# Generated by Django 5.2.6 on 2025-09-19 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_rescuerlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_id", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("ivr", "IVR (Voice Call)"),
                            ("ussd", "USSD"),
                            ("web", "Web Interface"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("bn", "Bengali"),
                            ("te", "Telugu"),
                            ("mr", "Marathi"),
                            ("ta", "Tamil"),
                            ("gu", "Gujarati"),
                            ("kn", "Kannada"),
                            ("ml", "Malayalam"),
                            ("pa", "Punjabi"),
                            ("or", "Odia"),
                            ("as", "Assamese"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "caller_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("flood", "Flood"),
                            ("landslide", "Landslide"),
                            ("roadblock", "Roadblock"),
                            ("medical", "Medical Emergency"),
                            ("fire", "Fire"),
                            ("earthquake", "Earthquake"),
                            ("cyclone", "Cyclone"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                    ),
                ),
                ("description", models.TextField()),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("false_alarm", "False Alarm"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("priority_score", models.FloatField(default=0.0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emergencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("acknowledgment", "Acknowledgment"),
                            ("update", "Status Update"),
                            ("resolution", "Resolution"),
                            ("escalation", "Escalation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emergency_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="backend.emergencyreport",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="emergencyreport",
            index=models.Index(
                fields=["status", "created_at"], name="backend_eme_status_39731c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyreport",
            index=models.Index(
                fields=["category", "severity"], name="backend_eme_categor_370703_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyreport",
            index=models.Index(
                fields=["phone_number"], name="backend_eme_phone_n_93d406_idx"
            ),
        ),
    ]
